import { GameRecord } from './types';

export const sampleRecords: GameRecord[] = [
  // 3-Cushion Games (15 games)
  {
    id: 's-1',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 12,
    innings: 18,
    highRun: 4,
    date: new Date(Date.now() - 86400000 * 0.5).toISOString(),
    average: 0.833,
    win: true,
    opponentName: '김당구'
  },
  {
    id: 's-2',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 11,
    opponentScore: 15,
    innings: 22,
    highRun: 3,
    date: new Date(Date.now() - 86400000 * 1.2).toISOString(),
    average: 0.500,
    win: false,
    opponentName: '박프로'
  },
  {
    id: 's-3',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 8,
    innings: 14,
    highRun: 6,
    date: new Date(Date.now() - 86400000 * 2.1).toISOString(),
    average: 1.071,
    win: true,
    opponentName: '이동수'
  },
  {
    id: 's-4',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 3,
    myScore: 15,
    opponentScore: 14,
    innings: 25,
    highRun: 4,
    date: new Date(Date.now() - 86400000 * 3.5).toISOString(),
    average: 0.600,
    win: true,
    rank: 1,
    opponentName: '박프로, 김당구'
  },
  {
    id: 's-5',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 14,
    innings: 20,
    highRun: 5,
    date: new Date(Date.now() - 86400000 * 4.8).toISOString(),
    average: 0.750,
    win: true,
    opponentName: '김당구'
  },
  {
    id: 's-6',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 9,
    opponentScore: 15,
    innings: 28,
    highRun: 2,
    date: new Date(Date.now() - 86400000 * 5.2).toISOString(),
    average: 0.321,
    win: false,
    opponentName: '이동수'
  },
  {
    id: 's-7',
    type: '3-Cushion',
    mode: 'Team',
    playerCount: 4,
    myScore: 20,
    opponentScore: 19,
    innings: 18,
    highRun: 7,
    date: new Date(Date.now() - 86400000 * 6.7).toISOString(),
    average: 1.111,
    win: true,
    opponentName: '상대팀A'
  },
  {
    id: 's-8',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 10,
    innings: 19,
    highRun: 4,
    date: new Date(Date.now() - 86400000 * 8.1).toISOString(),
    average: 0.789,
    win: true,
    opponentName: '최고수'
  },
  {
    id: 's-9',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 13,
    opponentScore: 15,
    innings: 21,
    highRun: 3,
    date: new Date(Date.now() - 86400000 * 9.5).toISOString(),
    average: 0.619,
    win: false,
    opponentName: '박프로'
  },
  {
    id: 's-10',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 13,
    innings: 17,
    highRun: 5,
    date: new Date(Date.now() - 86400000 * 11.2).toISOString(),
    average: 0.882,
    win: true,
    opponentName: '김당구'
  },
  {
    id: 's-11',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 3,
    myScore: 12,
    opponentScore: 15,
    innings: 24,
    highRun: 3,
    date: new Date(Date.now() - 86400000 * 13.4).toISOString(),
    average: 0.500,
    win: false,
    rank: 2,
    opponentName: '박프로, 최무림'
  },
  {
    id: 's-12',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 7,
    innings: 12,
    highRun: 8,
    date: new Date(Date.now() - 86400000 * 15.1).toISOString(),
    average: 1.250,
    win: true,
    opponentName: '이신입'
  },
  {
    id: 's-13',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 8,
    opponentScore: 15,
    innings: 20,
    highRun: 2,
    date: new Date(Date.now() - 86400000 * 17.8).toISOString(),
    average: 0.400,
    win: false,
    opponentName: '이신입'
  },
  {
    id: 's-14',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 15,
    opponentScore: 14,
    innings: 26,
    highRun: 3,
    date: new Date(Date.now() - 86400000 * 20.2).toISOString(),
    average: 0.577,
    win: true,
    opponentName: '김당구'
  },
  {
    id: 's-15',
    type: '3-Cushion',
    mode: 'Individual',
    playerCount: 2,
    myScore: 10,
    opponentScore: 15,
    innings: 22,
    highRun: 4,
    date: new Date(Date.now() - 86400000 * 25.5).toISOString(),
    average: 0.454,
    win: false,
    opponentName: '최고수'
  },

  // 4-Ball Games (15 games)
  {
    id: 's-16',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 180,
    innings: 12,
    highRun: 45,
    date: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    average: 16.667,
    win: true,
    lastThreeCushions: 1,
    opponentName: '강기수'
  },
  {
    id: 's-17',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 150,
    opponentScore: 200,
    innings: 15,
    highRun: 30,
    date: new Date(Date.now() - 86400000 * 3.2).toISOString(),
    average: 10.000,
    win: false,
    lastThreeCushions: 2,
    opponentName: '이동수'
  },
  {
    id: 's-18',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 250,
    opponentScore: 220,
    innings: 14,
    highRun: 65,
    date: new Date(Date.now() - 86400000 * 5.8).toISOString(),
    average: 17.857,
    win: true,
    lastThreeCushions: 0,
    opponentName: '박프로'
  },
  {
    id: 's-19',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 180,
    opponentScore: 200,
    innings: 20,
    highRun: 22,
    date: new Date(Date.now() - 86400000 * 8.4).toISOString(),
    average: 9.000,
    win: false,
    lastThreeCushions: 1,
    opponentName: '김당구'
  },
  {
    id: 's-20',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 140,
    innings: 10,
    highRun: 55,
    date: new Date(Date.now() - 86400000 * 10.1).toISOString(),
    average: 20.000,
    win: true,
    lastThreeCushions: 2,
    opponentName: '이신입'
  },
  {
    id: 's-21',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 3,
    myScore: 200,
    opponentScore: 190,
    innings: 18,
    highRun: 42,
    date: new Date(Date.now() - 86400000 * 12.5).toISOString(),
    average: 11.111,
    win: true,
    rank: 1,
    lastThreeCushions: 0,
    opponentName: '김당구, 박프로'
  },
  {
    id: 's-22',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 170,
    opponentScore: 200,
    innings: 22,
    highRun: 28,
    date: new Date(Date.now() - 86400000 * 15.2).toISOString(),
    average: 7.727,
    win: false,
    lastThreeCushions: 0,
    opponentName: '이동수'
  },
  {
    id: 's-23',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 120,
    innings: 11,
    highRun: 48,
    date: new Date(Date.now() - 86400000 * 18.7).toISOString(),
    average: 18.182,
    win: true,
    lastThreeCushions: 1,
    opponentName: '강기수'
  },
  {
    id: 's-24',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 195,
    innings: 16,
    highRun: 35,
    date: new Date(Date.now() - 86400000 * 22.4).toISOString(),
    average: 12.500,
    win: true,
    lastThreeCushions: 2,
    opponentName: '박프로'
  },
  {
    id: 's-25',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 140,
    opponentScore: 200,
    innings: 20,
    highRun: 18,
    date: new Date(Date.now() - 86400000 * 25.1).toISOString(),
    average: 7.000,
    win: false,
    lastThreeCushions: 1,
    opponentName: '김당구'
  },
  {
    id: 's-26',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 3,
    myScore: 180,
    opponentScore: 200,
    innings: 25,
    highRun: 31,
    date: new Date(Date.now() - 86400000 * 28.8).toISOString(),
    average: 7.200,
    win: false,
    rank: 2,
    lastThreeCushions: 0,
    opponentName: '최고수, 이신입'
  },
  {
    id: 's-27',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 150,
    innings: 13,
    highRun: 52,
    date: new Date(Date.now() - 86400000 * 32.1).toISOString(),
    average: 15.385,
    win: true,
    lastThreeCushions: 1,
    opponentName: '최고수'
  },
  {
    id: 's-28',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 110,
    opponentScore: 200,
    innings: 18,
    highRun: 25,
    date: new Date(Date.now() - 86400000 * 35.5).toISOString(),
    average: 6.111,
    win: false,
    lastThreeCushions: 2,
    opponentName: '강기수'
  },
  {
    id: 's-29',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 185,
    innings: 14,
    highRun: 39,
    date: new Date(Date.now() - 86400000 * 39.2).toISOString(),
    average: 14.286,
    win: true,
    lastThreeCushions: 0,
    opponentName: '박프로'
  },
  {
    id: 's-30',
    type: '4-Ball',
    mode: 'Individual',
    playerCount: 2,
    myScore: 200,
    opponentScore: 160,
    innings: 12,
    highRun: 58,
    date: new Date(Date.now() - 86400000 * 43.1).toISOString(),
    average: 16.667,
    win: true,
    lastThreeCushions: 1,
    opponentName: '김당구'
  }
];
